name: "Deploy para VPS"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixa o codigo"
        uses: actions/checkout@v4
        
      - name: "Copia arquivos via SSH"
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.IP_SERVER_NERDY }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_format: base64
          source: "."
          target: Nerdy
      
      - name: "Inicia Aplicacao"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER_NERDY }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_format: base64
          source: "."
          script: |
            apk add --no-cache py3-pip  # py3-pip, não só "pip"
      
            cd Nerdy
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            python3 nerdy_web/Aplicacao_WEB/database/init_db.py
            
            # Mata o processo anterior se estiver rodando
            # pkill -f "main.py" || true
            
            # Roda em background e mantém mesmo após SSH fechar
            nohup python3 nerdy_web/Aplicacao_WEB/main.py > /var/log/nerdy.log 2>&1 &